rezult111 : 5_laba.o vela lib
	gcc 5_laba.o -L. -lwwela222 -o rezult2227
5_laba.o :
	gcc -c 5_laba.c
vela : f1.o
	ar rc libwwela222.a del.o pro.o
f1.o :
	gcc -c  del.c pro.c
lib :
	ranlib libwwela222.a
clean :
	rm  5_laba.o del.o pro.o libwwela222.a rezult2227
